# greylistVote by ellbristow
# 
# For development updates, visit
# http://github.com/ellbristow/greylistvote
# 
# Plugin Configuration
# 
# required_votes: How many votes are needed to be approved?
# griefer_votes: How many votes are needed before approval is revoked?

required_votes: 2
griefer_votes: 3
