name: GreylistVote
main: me.ellbristow.greylistVote.greylistVote
version: 0.3.1
author: ellbristow
description: >
             Control the build rights of new players using votes
commands:
  greylist:
    description: Vote for a greylisted player.
    permission: greylistvote.vote
    usage: "/<command> [player]"
    aliases: gl
  votelist:
    description: Show who has already voted for the player.
    permission: greylistvote.list
    usage: "/<command> {player}"
    aliases: glvlist
  griefer:
    description: Vote for a player to be demoted for griefing.
    permission: greylistvote.griefer
    usage: "/<command> [player]"
permissions:
  greylistvote.*:
    description: Access to all GreylistVote commands
    children:
      greylistvote.approved: true
      greylistvote.vote: true
      greylistvote.list: true
      greylistvote.griefer: true
  greylistvote.approved:
    description: Player is approved to build.
  greylistvote.vote:
    description: Player can vote for a greylisted player.
  greylistvote.list:
    description: Player can use /votelist command
  greylistvote.griefer:
    description: Access to the /griefer command
